# Generated by Django 3.2.6 on 2021-08-19 08:30

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Ответы',
                'verbose_name_plural': 'Ответ',
            },
        ),
        migrations.CreateModel(
            name='IntegerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suitintnums', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=1)),
            ],
            options={
                'verbose_name': 'числовые ответы',
                'verbose_name_plural': 'числовой ответ',
            },
        ),
        migrations.CreateModel(
            name='MultipleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 1.1'), (2, 'Item title 1.2'), (3, 'Item title 1.3'), (4, 'Item title 1.4'), (5, 'Item title 1.5')], max_length=10)),
                ('my_field2', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], max_length=10)),
            ],
            options={
                'verbose_name': 'multi ответы',
                'verbose_name_plural': 'Несколько ответов',
            },
        ),
        migrations.CreateModel(
            name='SelfAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=255, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Собственные ответы',
                'verbose_name_plural': 'Собственный ответ',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('description', models.TextField(default='', help_text='описание вопроса', verbose_name='описнаие')),
                ('complexity', models.IntegerField(choices=[(0, 'low'), (1, 'normal'), (2, 'high')], default=0)),
                ('answer', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='course.answer')),
            ],
            options={
                'verbose_name': 'Вопросы',
                'verbose_name_plural': 'Вопрос',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='integer_answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='course.integeranswer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='multi_answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='course.multipleanswer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='self_answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='course.selfanswer'),
        ),
        migrations.CreateModel(
            name='CreateCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название курса', max_length=50, verbose_name='назавние курса')),
                ('description', models.TextField(default='', help_text='Описание курса')),
                ('complexity', models.IntegerField(choices=[(0, 'low'), (1, 'normal'), (2, 'high')], help_text='сложность')),
                ('num_of_questions', models.CharField(help_text='количество вопросов', max_length=2, verbose_name='количество вопросов')),
                ('select_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='course.question')),
            ],
            options={
                'verbose_name': 'создание курсов',
                'verbose_name_plural': 'создание курса',
            },
        ),
    ]
